apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-pv-volume
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/smithlu7/mnt/data/images"
