{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fridgehub.serviceAccountName" . }}
  labels:
{{ include "fridgehub.labels" . | nindent 4 }}
{{- end -}}
