apiVersion: v1
kind: Service
metadata:
  name: {{ include "fridgehub.fullname" . }}-ingredient-service
  labels:
    {{- include "fridgehub.labels" . | nindent 4 }}.ingredient-service
spec:
  type: ClusterIP
  ports:
    - port: 28080
      targetPort: 28080
      protocol: TCP
  selector:
    app: {{ include "fridgehub.fullname" . }}.ingredient-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fridgehub.fullname" . }}-profile-service
  labels:
    {{- include "fridgehub.labels" . | nindent 4 }}.profile-service
spec:
  type: ClusterIP
  ports:
    - port: 28080
      targetPort: 28080
      protocol: TCP
  selector:
    app: {{ include "fridgehub.fullname" . }}.profile-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fridgehub.fullname" . }}-recipe-service
  labels:
    {{- include "fridgehub.labels" . | nindent 4 }}.recipe-service
spec:
  type: ClusterIP
  ports:
    - port: 28080
      targetPort: 28080
      protocol: TCP
  selector:
    app: {{ include "fridgehub.fullname" . }}.recipe-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fridgehub.fullname" . }}-challenge-service
  labels:
    {{- include "fridgehub.labels" . | nindent 4 }}.challenge-service
spec:
  type: ClusterIP
  ports:
    - port: 28080
      targetPort: 28080
      protocol: TCP
  selector:
    app: {{ include "fridgehub.fullname" . }}.challenge-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fridgehub.fullname" . }}-web-ui
  labels:
    {{- include "fridgehub.labels" . | nindent 4 }}.web-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "fridgehub.fullname" . }}.web-ui
