-- CREATE USER rcp WITH PASSWORD 'rcp';

drop table Category if exists;
drop table Comments if exists;
drop table Ingredients if exists;
drop table Ratings if exists;
drop table Steps if exists;
drop table Recipe if exists;
drop sequence if exists RECIPE_SEQ;
drop sequence if exists CATEGORY_SEQ;
drop sequence if exists COMMENTS_SEQ;
drop sequence if exists INGREDIENTS_SEQ;
drop sequence if exists RATINGS_SEQ;
drop sequence if exists STEPS_SEQ;
create sequence CATEGORY_SEQ start with 1 increment by 50;
create sequence COMMENTS_SEQ start with 1 increment by 50;
create sequence INGREDIENTS_SEQ start with 1 increment by 50;
create sequence RATINGS_SEQ start with 1 increment by 50;
create sequence STEPS_SEQ start with 1 increment by 50;
create sequence RECIPE_SEQ start with 1 increment by 1;
create table Recipe (
    id bigint generated by default as identity,
    authorID bigint,
    date varchar(255),
    difficulty integer not null,
    name varchar(255),
    time integer not null,
    primary key (id)
);
create table Category (
    id bigint not null,
    category integer,
    Recipe_ID bigint,
    primary key (id)
);

create table Comments (
    id bigint not null,
    comment varchar(255),
    Recipe_ID bigint,
    primary key (id)
);

create table Ingredients (
    id bigint not null,
    IngredientID bigint not null,
    quantite integer not null,
    Recipe_ID bigint,
    primary key (id)
);

create table Ratings (
    id bigint not null,
    rate integer not null,
    Recipe_ID bigint,
    primary key (id)
);

create table Steps (
    id bigint not null,
    steps varchar(255),
    Recipe_id bigint,
    primary key (id)
);

alter table Category
    add constraint FK3id5k3clok8i99x858e0au3oc
    foreign key (Recipe_ID)
    references Recipe;

alter table Comments
    add constraint FKitod1h0fmt0dfg3399h3hl3vx
    foreign key (Recipe_ID)
    references Recipe;

alter table Ingredients
    add constraint FKpx948xuk56dhbwrt0owopr8au
    foreign key (Recipe_ID)
    references Recipe;

alter table Ratings
    add constraint FK8bdfwavk430j695y0v6f1nwc2
    foreign key (Recipe_ID)
    references Recipe;

alter table Steps
    add constraint FK1f9l28viiu893aug0bi3d4ji6
    foreign key (Recipe_id)
    references Recipe;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public to rcp;
GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public to rcp;
TRUNCATE TABLE RECIPE;
